/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package com.kontext;

public final class R {
    public static final class attr {
        public static final int adSize = 0x7f030022;
        public static final int adSizes = 0x7f030023;
        public static final int adUnitId = 0x7f030024;
        public static final int buttonSize = 0x7f03004b;
        public static final int circleCrop = 0x7f030058;
        public static final int colorScheme = 0x7f030069;
        public static final int font = 0x7f0300a4;
        public static final int fontProviderAuthority = 0x7f0300a6;
        public static final int fontProviderCerts = 0x7f0300a7;
        public static final int fontProviderFetchStrategy = 0x7f0300a8;
        public static final int fontProviderFetchTimeout = 0x7f0300a9;
        public static final int fontProviderPackage = 0x7f0300aa;
        public static final int fontProviderQuery = 0x7f0300ab;
        public static final int fontStyle = 0x7f0300ac;
        public static final int fontWeight = 0x7f0300ad;
        public static final int imageAspectRatio = 0x7f0300bd;
        public static final int imageAspectRatioAdjust = 0x7f0300be;
        public static final int scopeUris = 0x7f030135;
    }
    public static final class bool {
        public static final int abc_action_bar_embed_tabs = 0x7f040000;
    }
    public static final class color {
        public static final int common_google_signin_btn_text_dark = 0x7f05003d;
        public static final int common_google_signin_btn_text_dark_default = 0x7f05003e;
        public static final int common_google_signin_btn_text_dark_disabled = 0x7f05003f;
        public static final int common_google_signin_btn_text_dark_focused = 0x7f050040;
        public static final int common_google_signin_btn_text_dark_pressed = 0x7f050041;
        public static final int common_google_signin_btn_text_light = 0x7f050042;
        public static final int common_google_signin_btn_text_light_default = 0x7f050043;
        public static final int common_google_signin_btn_text_light_disabled = 0x7f050044;
        public static final int common_google_signin_btn_text_light_focused = 0x7f050045;
        public static final int common_google_signin_btn_text_light_pressed = 0x7f050046;
        public static final int common_google_signin_btn_tint = 0x7f050047;
        public static final int notification_action_color_filter = 0x7f050070;
        public static final int notification_icon_bg_color = 0x7f050071;
        public static final int notification_material_background_media_default_color = 0x7f050072;
        public static final int primary_text_default_material_dark = 0x7f050077;
        public static final int ripple_material_light = 0x7f05007c;
        public static final int secondary_text_default_material_dark = 0x7f05007d;
        public static final int secondary_text_default_material_light = 0x7f05007e;
    }
    public static final class dimen {
        public static final int compat_button_inset_horizontal_material = 0x7f06004f;
        public static final int compat_button_inset_vertical_material = 0x7f060050;
        public static final int compat_button_padding_horizontal_material = 0x7f060051;
        public static final int compat_button_padding_vertical_material = 0x7f060052;
        public static final int compat_control_corner_material = 0x7f060053;
        public static final int notification_action_icon_size = 0x7f06008e;
        public static final int notification_action_text_size = 0x7f06008f;
        public static final int notification_big_circle_margin = 0x7f060090;
        public static final int notification_content_margin_start = 0x7f060091;
        public static final int notification_large_icon_height = 0x7f060092;
        public static final int notification_large_icon_width = 0x7f060093;
        public static final int notification_main_column_padding_top = 0x7f060094;
        public static final int notification_media_narrow_margin = 0x7f060095;
        public static final int notification_right_icon_size = 0x7f060096;
        public static final int notification_right_side_padding_top = 0x7f060097;
        public static final int notification_small_icon_background_padding = 0x7f060098;
        public static final int notification_small_icon_size_as_large = 0x7f060099;
        public static final int notification_subtext_size = 0x7f06009a;
        public static final int notification_top_pad = 0x7f06009b;
        public static final int notification_top_pad_large_text = 0x7f06009c;
    }
    public static final class drawable {
        public static final int common_full_open_on_phone = 0x7f070066;
        public static final int common_google_signin_btn_icon_dark = 0x7f070067;
        public static final int common_google_signin_btn_icon_dark_focused = 0x7f070068;
        public static final int common_google_signin_btn_icon_dark_normal = 0x7f070069;
        public static final int common_google_signin_btn_icon_dark_normal_background = 0x7f07006a;
        public static final int common_google_signin_btn_icon_disabled = 0x7f07006b;
        public static final int common_google_signin_btn_icon_light = 0x7f07006c;
        public static final int common_google_signin_btn_icon_light_focused = 0x7f07006d;
        public static final int common_google_signin_btn_icon_light_normal = 0x7f07006e;
        public static final int common_google_signin_btn_icon_light_normal_background = 0x7f07006f;
        public static final int common_google_signin_btn_text_dark = 0x7f070070;
        public static final int common_google_signin_btn_text_dark_focused = 0x7f070071;
        public static final int common_google_signin_btn_text_dark_normal = 0x7f070072;
        public static final int common_google_signin_btn_text_dark_normal_background = 0x7f070073;
        public static final int common_google_signin_btn_text_disabled = 0x7f070074;
        public static final int common_google_signin_btn_text_light = 0x7f070075;
        public static final int common_google_signin_btn_text_light_focused = 0x7f070076;
        public static final int common_google_signin_btn_text_light_normal = 0x7f070077;
        public static final int common_google_signin_btn_text_light_normal_background = 0x7f070078;
        public static final int googleg_disabled_color_18 = 0x7f070091;
        public static final int googleg_standard_color_18 = 0x7f070092;
        public static final int ic_os_notification_fallback_white_24dp = 0x7f070098;
        public static final int notification_action_background = 0x7f0700b1;
        public static final int notification_bg = 0x7f0700b2;
        public static final int notification_bg_low = 0x7f0700b3;
        public static final int notification_bg_low_normal = 0x7f0700b4;
        public static final int notification_bg_low_pressed = 0x7f0700b5;
        public static final int notification_bg_normal = 0x7f0700b6;
        public static final int notification_bg_normal_pressed = 0x7f0700b7;
        public static final int notification_icon_background = 0x7f0700b8;
        public static final int notification_template_icon_bg = 0x7f0700b9;
        public static final int notification_template_icon_low_bg = 0x7f0700ba;
        public static final int notification_tile_bg = 0x7f0700bb;
        public static final int notify_panel_notification_icon_bg = 0x7f0700bc;
    }
    public static final class id {
        public static final int action0 = 0x7f080006;
        public static final int action_container = 0x7f08000e;
        public static final int action_divider = 0x7f080010;
        public static final int action_image = 0x7f080011;
        public static final int action_text = 0x7f080018;
        public static final int actions = 0x7f080019;
        public static final int adjust_height = 0x7f08001c;
        public static final int adjust_width = 0x7f08001d;
        public static final int async = 0x7f080021;
        public static final int auto = 0x7f080022;
        public static final int blocking = 0x7f080025;
        public static final int cancel_action = 0x7f080028;
        public static final int center = 0x7f08002b;
        public static final int chronometer = 0x7f080030;
        public static final int dark = 0x7f080039;
        public static final int end_padder = 0x7f080046;
        public static final int forever = 0x7f080055;
        public static final int icon = 0x7f08005a;
        public static final int icon_group = 0x7f08005b;
        public static final int icon_only = 0x7f08005c;
        public static final int info = 0x7f08005f;
        public static final int italic = 0x7f080060;
        public static final int light = 0x7f080064;
        public static final int line1 = 0x7f080065;
        public static final int line3 = 0x7f080066;
        public static final int media_actions = 0x7f080070;
        public static final int none = 0x7f080082;
        public static final int normal = 0x7f080083;
        public static final int notification_background = 0x7f080084;
        public static final int notification_main_column = 0x7f080089;
        public static final int notification_main_column_container = 0x7f08008a;
        public static final int os_bgimage_notif_bgimage = 0x7f08008e;
        public static final int os_bgimage_notif_bgimage_align_layout = 0x7f08008f;
        public static final int os_bgimage_notif_bgimage_right_aligned = 0x7f080090;
        public static final int os_bgimage_notif_body = 0x7f080091;
        public static final int os_bgimage_notif_title = 0x7f080092;
        public static final int radio = 0x7f08009b;
        public static final int right_icon = 0x7f08009d;
        public static final int right_side = 0x7f08009e;
        public static final int standard = 0x7f0800c5;
        public static final int status_bar_latest_event_content = 0x7f0800c7;
        public static final int text = 0x7f0800cb;
        public static final int text2 = 0x7f0800cc;
        public static final int time = 0x7f0800d3;
        public static final int title = 0x7f0800d4;
        public static final int wide = 0x7f0800e5;
        public static final int wrap_content = 0x7f0800e8;
    }
    public static final class integer {
        public static final int cancel_button_image_alpha = 0x7f090004;
        public static final int google_play_services_version = 0x7f090007;
        public static final int status_bar_notification_info_maxnum = 0x7f09000a;
    }
    public static final class layout {
        public static final int kontext_bgimage_notif_layout = 0x7f0a002d;
        public static final int notification_action = 0x7f0a0032;
        public static final int notification_action_tombstone = 0x7f0a0033;
        public static final int notification_media_action = 0x7f0a0034;
        public static final int notification_media_cancel_action = 0x7f0a0035;
        public static final int notification_template_big_media = 0x7f0a0036;
        public static final int notification_template_big_media_custom = 0x7f0a0037;
        public static final int notification_template_big_media_narrow = 0x7f0a0038;
        public static final int notification_template_big_media_narrow_custom = 0x7f0a0039;
        public static final int notification_template_custom_big = 0x7f0a003a;
        public static final int notification_template_icon_group = 0x7f0a003b;
        public static final int notification_template_lines_media = 0x7f0a003c;
        public static final int notification_template_media = 0x7f0a003d;
        public static final int notification_template_media_custom = 0x7f0a003e;
        public static final int notification_template_part_chronometer = 0x7f0a003f;
        public static final int notification_template_part_time = 0x7f0a0040;
    }
    public static final class raw {
        public static final int consumer_kontext_keep = 0x7f0d0000;
    }
    public static final class string {
        public static final int common_google_play_services_enable_button = 0x7f0e0025;
        public static final int common_google_play_services_enable_text = 0x7f0e0026;
        public static final int common_google_play_services_enable_title = 0x7f0e0027;
        public static final int common_google_play_services_install_button = 0x7f0e0028;
        public static final int common_google_play_services_install_text = 0x7f0e0029;
        public static final int common_google_play_services_install_title = 0x7f0e002a;
        public static final int common_google_play_services_notification_ticker = 0x7f0e002b;
        public static final int common_google_play_services_unknown_issue = 0x7f0e002c;
        public static final int common_google_play_services_unsupported_text = 0x7f0e002d;
        public static final int common_google_play_services_update_button = 0x7f0e002e;
        public static final int common_google_play_services_update_text = 0x7f0e002f;
        public static final int common_google_play_services_update_title = 0x7f0e0030;
        public static final int common_google_play_services_updating_text = 0x7f0e0031;
        public static final int common_google_play_services_wear_update_text = 0x7f0e0032;
        public static final int common_open_on_phone = 0x7f0e0033;
        public static final int common_signin_button_text = 0x7f0e0034;
        public static final int common_signin_button_text_long = 0x7f0e0035;
        public static final int gcm_fallback_notification_channel_label = 0x7f0e0039;
        public static final int s1 = 0x7f0e0046;
        public static final int s2 = 0x7f0e0047;
        public static final int s3 = 0x7f0e0048;
        public static final int s4 = 0x7f0e0049;
        public static final int s5 = 0x7f0e004a;
        public static final int s6 = 0x7f0e004b;
        public static final int status_bar_notification_info_overflow = 0x7f0e004f;
    }
    public static final class style {
        public static final int TextAppearance_Compat_Notification = 0x7f0f0105;
        public static final int TextAppearance_Compat_Notification_Info = 0x7f0f0106;
        public static final int TextAppearance_Compat_Notification_Info_Media = 0x7f0f0107;
        public static final int TextAppearance_Compat_Notification_Line2 = 0x7f0f0108;
        public static final int TextAppearance_Compat_Notification_Line2_Media = 0x7f0f0109;
        public static final int TextAppearance_Compat_Notification_Media = 0x7f0f010a;
        public static final int TextAppearance_Compat_Notification_Time = 0x7f0f010b;
        public static final int TextAppearance_Compat_Notification_Time_Media = 0x7f0f010c;
        public static final int TextAppearance_Compat_Notification_Title = 0x7f0f010d;
        public static final int TextAppearance_Compat_Notification_Title_Media = 0x7f0f010e;
        public static final int Theme_IAPTheme = 0x7f0f0134;
        public static final int Widget_Compat_NotificationActionContainer = 0x7f0f0185;
        public static final int Widget_Compat_NotificationActionText = 0x7f0f0186;
    }
    public static final class styleable {
        public static final int[] AdsAttrs = { 0x7f030022, 0x7f030023, 0x7f030024 };
        public static final int AdsAttrs_adSize = 0;
        public static final int AdsAttrs_adSizes = 1;
        public static final int AdsAttrs_adUnitId = 2;
        public static final int[] FontFamily = { 0x7f0300a6, 0x7f0300a7, 0x7f0300a8, 0x7f0300a9, 0x7f0300aa, 0x7f0300ab };
        public static final int FontFamily_fontProviderAuthority = 0;
        public static final int FontFamily_fontProviderCerts = 1;
        public static final int FontFamily_fontProviderFetchStrategy = 2;
        public static final int FontFamily_fontProviderFetchTimeout = 3;
        public static final int FontFamily_fontProviderPackage = 4;
        public static final int FontFamily_fontProviderQuery = 5;
        public static final int[] FontFamilyFont = { 0x7f0300a4, 0x7f0300ac, 0x7f0300ad };
        public static final int FontFamilyFont_font = 0;
        public static final int FontFamilyFont_fontStyle = 1;
        public static final int FontFamilyFont_fontWeight = 2;
        public static final int[] LoadingImageView = { 0x7f030058, 0x7f0300bd, 0x7f0300be };
        public static final int LoadingImageView_circleCrop = 0;
        public static final int LoadingImageView_imageAspectRatio = 1;
        public static final int LoadingImageView_imageAspectRatioAdjust = 2;
        public static final int[] SignInButton = { 0x7f03004b, 0x7f030069, 0x7f030135 };
        public static final int SignInButton_buttonSize = 0;
        public static final int SignInButton_colorScheme = 1;
        public static final int SignInButton_scopeUris = 2;
    }
}
